#' Splink Fake 1000 — Deduplication Benchmark
#'
#' A dataset of 1,000 synthetic records representing 181 unique people,
#' each with varying numbers of duplicate entries.
#' Duplicates have been corrupted with typographical errors, missing values,
#' and other realistic data-quality issues.
#' This is the primary demo dataset from the Python
#' \href{https://github.com/moj-analytical-services/splink}{splink} library.
#'
#' The `cluster` column provides ground-truth entity labels: records sharing
#' the same cluster value refer to the same person.
#' The `unique_id` column provides a unique identifier for each row,
#' starting at 0 (matching splink convention).
#'
#' @format A tibble with 1,000 rows and 7 columns:
#' \describe{
#'   \item{unique_id}{Integer. Row identifier (0-indexed).}
#'   \item{first_name}{Character. Given name, sometimes corrupted or missing.}
#'   \item{surname}{Character. Family name, sometimes corrupted or missing.}
#'   \item{dob}{Character. Date of birth in `YYYY-MM-DD` format.}
#'   \item{city}{Character. City of residence, sometimes missing.}
#'   \item{email}{Character. Email address, sometimes corrupted or missing.}
#'   \item{cluster}{Integer. Ground-truth entity label (0-indexed).}
#' }
#'
#' @source
#' From the splink datasets repository maintained by the UK Ministry of
#' Justice Analytical Services:
#' <https://github.com/moj-analytical-services/splink_datasets>.
#' Original data generated by the splink team (Linacre et al.) under the
#' MIT licence.
#'
#' @seealso [fake_1000_labels] for pairwise clerical labels.
'fake_1000'


#' Splink Fake 1000 — Clerical Pairwise Labels
#'
#' Pairwise clerical labels for the [fake_1000] dataset.
#' Each row records whether a pair of records from `fake_1000` is a true
#' match (`clerical_match_score = 1`) or a non-match
#' (`clerical_match_score = 0`).
#' These labels enable evaluation of model accuracy, ROC curves, and
#' precision–recall metrics.
#'
#' @format A tibble with 3,176 rows and 5 columns:
#' \describe{
#'   \item{unique_id_l}{Integer. `unique_id` of the left record.}
#'   \item{source_dataset_l}{Character. Source dataset name (`"fake_1000"`).}
#'   \item{unique_id_r}{Integer. `unique_id` of the right record.}
#'   \item{source_dataset_r}{Character. Source dataset name (`"fake_1000"`).}
#'   \item{clerical_match_score}{Numeric. 1 for a match, 0 for a non-match.}
#' }
#'
#' @source
#' From the splink datasets repository maintained by the UK Ministry of
#' Justice Analytical Services:
#' <https://github.com/moj-analytical-services/splink_datasets>.
#' Original data generated by the splink team (Linacre et al.) under the
#' MIT licence.
#'
#' @seealso [fake_1000], [il_accuracy()], [il_roc()],
#'   [il_precision_recall()].
'fake_1000_labels'


#' FEBRL 4a — Record Linkage Original Records
#'
#' The FEBRL (Freely Extensible Biomedical Record Linkage) dataset 4a
#' contains 5,000 original records.
#' It is designed to be linked against [febrl4b], which contains one
#' duplicate record per original.
#' Ground truth is encoded in `rec_id`: records sharing the same base ID
#' (e.g., `rec-1070-org` and `rec-1070-dup-0`) refer to the same entity.
#'
#' @format A tibble with 5,000 rows and 11 columns:
#' \describe{
#'   \item{rec_id}{Character. Record identifier encoding entity and
#'     origin (`-org` suffix).}
#'   \item{given_name}{Character. Given name, sometimes missing.}
#'   \item{surname}{Character. Family name, sometimes missing.}
#'   \item{street_number}{Integer. Street number, sometimes missing.}
#'   \item{address_1}{Character. Primary address line, sometimes missing.}
#'   \item{address_2}{Character. Secondary address line, often missing.}
#'   \item{suburb}{Character. Suburb or neighbourhood.}
#'   \item{postcode}{Integer. Postal code.}
#'   \item{state}{Character. Australian state abbreviation.}
#'   \item{date_of_birth}{Integer. Date of birth as `YYYYMMDD` integer,
#'     sometimes missing.}
#'   \item{soc_sec_id}{Integer. Social security identifier.}
#' }
#'
#' @source
#' Distributed via the splink datasets repository
#' (<https://github.com/moj-analytical-services/splink_datasets>)
#' under the MIT licence.
#' The FEBRL datasets originate from Christen and Churches (2004)
#' and are widely used as record-linkage benchmarks.
#'
#' @references
#' Christen, P. and Churches, T. (2004).
#' Febrl -- Freely Extensible Biomedical Record Linkage.
#' Australian National University.
#'
#' @seealso [febrl4b] for the corresponding duplicate records.
'febrl4a'


#' FEBRL 4b — Record Linkage Duplicate Records
#'
#' The FEBRL (Freely Extensible Biomedical Record Linkage) dataset 4b
#' contains 5,000 duplicate records, one for each original in [febrl4a].
#' Duplicates have been corrupted with typographical errors, missing
#' values, and transpositions.
#' Ground truth is encoded in `rec_id`: the base number matches the
#' corresponding original (e.g., `rec-1070-dup-0` matches
#' `rec-1070-org`).
#'
#' @format A tibble with 5,000 rows and 11 columns:
#' \describe{
#'   \item{rec_id}{Character. Record identifier encoding entity and
#'     duplicate status (`-dup-0` suffix).}
#'   \item{given_name}{Character. Given name, sometimes corrupted or
#'     missing.}
#'   \item{surname}{Character. Family name, sometimes corrupted or
#'     missing.}
#'   \item{street_number}{Integer. Street number, sometimes missing.}
#'   \item{address_1}{Character. Primary address line, sometimes
#'     corrupted.}
#'   \item{address_2}{Character. Secondary address line, often missing.}
#'   \item{suburb}{Character. Suburb or neighbourhood.}
#'   \item{postcode}{Integer. Postal code.}
#'   \item{state}{Character. Australian state abbreviation.}
#'   \item{date_of_birth}{Integer. Date of birth as `YYYYMMDD` integer,
#'     sometimes missing.}
#'   \item{soc_sec_id}{Integer. Social security identifier.}
#' }
#'
#' @source
#' Distributed via the splink datasets repository
#' (<https://github.com/moj-analytical-services/splink_datasets>)
#' under the MIT licence.
#' The FEBRL datasets originate from Christen and Churches (2004)
#' and are widely used as record-linkage benchmarks.
#'
#' @references
#' Christen, P. and Churches, T. (2004).
#' Febrl -- Freely Extensible Biomedical Record Linkage.
#' Australian National University.
#'
#' @seealso [febrl4a] for the corresponding original records.
'febrl4b'


#' Fake 20 — Minimal Deduplication Example
#'
#' A small, hand-crafted dataset of 20 records representing 5 unique
#' people.
#' Each person has four records with varying levels of corruption:
#' exact matches, minor typos, and slightly shifted dates of birth.
#' Designed for quick examples and unit tests.
#'
#' @format A tibble with 20 rows and 6 columns:
#' \describe{
#'   \item{first_name}{Character. Given name, sometimes corrupted.}
#'   \item{surname}{Character. Family name, sometimes corrupted.}
#'   \item{dob}{Character. Date of birth in `YYYY-MM-DD` format,
#'     sometimes shifted by one day.}
#'   \item{city}{Character. City of residence.}
#'   \item{email}{Character. Email address, sometimes corrupted.}
#'   \item{cluster}{Integer. Ground-truth entity label (1 to 5).}
#' }
#'
#' @seealso [fake_1000] for a larger benchmark dataset.
'fake_20'
