#' Train Parameters via Expectation-Maximisation
#'
#' Runs the EM algorithm under a blocking rule to learn m and u parameters
#' from unlabelled data. Multiple calls with different blocking rules can
#' be chained to train on complementary subsets of record pairs — each
#' call updates the model cumulatively. Analogous to [parsnip::fit()] in
#' tidymodels.
#'
#' @param model An `il_model` object (piped in).
#' @param blocking A blocking rule created by [block_on()].
#' @param ... Reserved for future options (e.g., convergence tolerance,
#'   maximum iterations).
#'
#' @return An updated `il_model` with trained m and u parameters.
#' @export
#'
#' @examples
#' \dontrun{
#' model <- il_model(voters, spec = spec, con = con) |>
#'   il_estimate_u() |>
#'   il_estimate_em(block_on(first_name, surname)) |>
#'   il_estimate_em(block_on(dob))
#' }
il_estimate_em <- function(model, blocking, ...) {
  validate_il_model(model)
  pairs <- get_blocked_pairs(model, blocking)

  if (nrow(pairs) == 0L) {
    cli::cli_abort("No pairs generated by the blocking rule. Choose a less restrictive rule.")
  }

  comparisons <- model$spec$comparisons
  gamma_mat <- compute_gamma_matrix(pairs, comparisons)
  comp_names <- colnames(gamma_mat)
  n_comp <- ncol(gamma_mat)
  n_pairs <- nrow(pairs)

  # Initialize m and u
  params <- model$params$comparisons
  m_match <- rep(0.9, n_comp)
  m_nonmatch <- rep(0.1, n_comp)
  u_match <- rep(0.1, n_comp)
  u_nonmatch <- rep(0.9, n_comp)

  if (!is.null(params)) {
    for (j in seq_len(n_comp)) {
      cn <- comp_names[j]
      row_m <- params[params$comparison == cn & params$level == "match", ]
      row_nm <- params[params$comparison == cn & params$level == "non_match", ]
      if (nrow(row_m) > 0L && !is.na(row_m$m[1])) m_match[j] <- row_m$m[1]
      if (nrow(row_nm) > 0L && !is.na(row_nm$m[1])) m_nonmatch[j] <- row_nm$m[1]
      if (nrow(row_m) > 0L && !is.na(row_m$u[1])) u_match[j] <- row_m$u[1]
      if (nrow(row_nm) > 0L && !is.na(row_nm$u[1])) u_nonmatch[j] <- row_nm$u[1]
    }
  }

  prior <- model$params$prior %||% 0.05
  max_iter <- 25L
  tol <- 1e-5
  history <- list()

  for (iter in seq_len(max_iter)) {
    # E-step: compute posterior match probability
    log_match <- rep(log(prior), n_pairs)
    log_nonmatch <- rep(log(1 - prior), n_pairs)

    for (j in seq_len(n_comp)) {
      g <- gamma_mat[, j]
      lm_1 <- log(pmax(m_match[j], 1e-10))
      lm_0 <- log(pmax(m_nonmatch[j], 1e-10))
      lu_1 <- log(pmax(u_match[j], 1e-10))
      lu_0 <- log(pmax(u_nonmatch[j], 1e-10))

      log_match <- log_match + ifelse(g == 1L, lm_1, lm_0)
      log_nonmatch <- log_nonmatch + ifelse(g == 1L, lu_1, lu_0)
    }

    max_log <- pmax(log_match, log_nonmatch)
    weights <- exp(log_match - max_log) /
      (exp(log_match - max_log) + exp(log_nonmatch - max_log))

    # M-step: update m (u stays from estimate_u)
    sum_w <- sum(weights)
    sum_1mw <- sum(1 - weights)

    old_m_match <- m_match
    for (j in seq_len(n_comp)) {
      g <- gamma_mat[, j]
      # Laplace smoothing + clamping to prevent degenerate estimates
      raw <- (sum(weights * g) + 0.5) / (sum_w + 1.0)
      m_match[j] <- max(min(raw, 0.99), 0.01)
      m_nonmatch[j] <- 1 - m_match[j]
    }

    history[[iter]] <- tibble::tibble(
      iteration = iter,
      comparison = comp_names,
      level = "match",
      value = m_match
    )

    if (max(abs(m_match - old_m_match)) < tol) break
  }

  # Store updated parameters
  model$params$comparisons <- tibble::tibble(
    comparison = rep(comp_names, each = 2L),
    level = rep(c("match", "non_match"), times = n_comp),
    m = as.numeric(rbind(m_match, m_nonmatch)),
    u = as.numeric(rbind(u_match, u_nonmatch))
  )

  model$params$history <- c(model$params$history, history)
  model$trained <- TRUE
  model
}
