#' Train Parameters via Expectation-Maximisation
#'
#' Runs the EM algorithm under a blocking rule to learn m and u parameters
#' from unlabelled data. Multiple calls with different blocking rules can
#' be chained to train on complementary subsets of record pairs — each
#' call updates the model cumulatively.
#'
#' @param model An `il_model` object (piped in).
#' @param blocking A blocking rule created by [block_on()].
#' @param convergence A numeric convergence tolerance. The EM loop stops
#'   when the largest change in any updated parameter is below this value.
#'   Defaults to `1e-5`.
#' @param fix_u Logical. If `TRUE` (the default), hold u parameters fixed
#'   during EM — only m is updated. Set to `FALSE` to also estimate u.
#' @param fix_m Logical. If `TRUE`, hold m parameters fixed during EM.
#'   Defaults to `FALSE`. At least one of `fix_u` and `fix_m` must be
#'   `FALSE`, otherwise the algorithm cannot learn anything.
#' @param max_iterations Maximum number of EM iterations. Defaults to
#'   `25L`. The loop stops early when convergence is reached.
#' @param fix_prior Logical. If `TRUE`, hold the prior (probability that
#'   two random records match) fixed during EM iterations.
#'   Defaults to `TRUE`.
#' @param estimate_without_tf Logical. If `TRUE` (the default), EM runs
#'   on aggregated gamma-pattern counts (fast, but ignores per-pair term
#'   frequency variation). If `FALSE`, EM runs on individual pairs and
#'   incorporates per-pair TF adjustments in the E-step, matching
#'   splink's default behaviour. Only matters when at least one
#'   comparison has `term_frequency = TRUE`.
#' @param derive_prior Logical. If `TRUE`, derive the prior from the
#'   trained parameter values after EM completes and store it in the
#'   model. Defaults to `FALSE`.
#' @param ... Reserved for future options.
#'
#' @return An updated `il_model` with trained m and u parameters.
#' @export
#'
#' @examples
#' df <- data.frame(
#'   unique_id = 1:20,
#'   first_name = c(
#'     'John', 'Jon', 'Jane', 'Jane', 'Bob',
#'     'Bobby', 'Alice', 'Alicia', 'Tom', 'Thomas',
#'     'John', 'Jon', 'Jane', 'Janet', 'Bob',
#'     'Robert', 'Alice', 'Alison', 'Tom', 'Tomas'
#'   ),
#'   surname = c(
#'     'Smith', 'Smith', 'Doe', 'Doe', 'Jones',
#'     'Jones', 'Brown', 'Brown', 'White', 'White',
#'     'Smith', 'Smyth', 'Doe', 'Doe', 'Jones',
#'     'Jones', 'Brown', 'Browne', 'White', 'White'
#'   ),
#'   dob = c(
#'     '1990-01-01', '1990-01-01', '1985-06-15', '1985-06-15',
#'     '2000-12-01', '2000-12-01', '1975-03-22', '1975-03-22',
#'     '1988-07-04', '1988-07-04', '1990-01-01', '1990-01-02',
#'     '1985-06-15', '1985-06-16', '2000-12-01', '2000-12-02',
#'     '1975-03-22', '1975-03-23', '1988-07-04', '1988-07-05'
#'   ),
#'   city = c(
#'     'London', 'London', 'Paris', 'Paris', 'Berlin',
#'     'Berlin', 'Rome', 'Rome', 'Madrid', 'Madrid',
#'     'London', 'London', 'Paris', 'Paris', 'Berlin',
#'     'Berlin', 'Rome', 'Rome', 'Madrid', 'Madrid'
#'   ),
#'   email = c(
#'     'john@example.com', 'jon@example.com', 'jane@example.com',
#'     'jane@example.com', 'bob@example.com', 'bobby@example.com',
#'     'alice@example.com', 'alicia@example.com', 'tom@example.com',
#'     'thomas@example.com', 'john@example.com', 'jon@example.com',
#'     'jane@example.com', 'janet@example.com', 'bob@example.com',
#'     'robert@example.com', 'alice@example.com', 'alison@example.com',
#'     'tom@example.com', 'tomas@example.com'
#'   )
#' )
#' con <- DBI::dbConnect(duckdb::duckdb())
#' spec <- il_spec() |>
#'   il_compare(first_name, cl_jaro_winkler(0.9, 0.7)) |>
#'   il_compare(surname, cl_jaro_winkler(0.9, 0.7)) |>
#'   il_compare(dob, cl_exact()) |>
#'   il_block_on(surname) |>
#'   il_block_on(first_name)
#' model <- il_model(df, spec = spec, con = con)
#' model <- il_estimate_u(model)
#'
#' model <- il_estimate_em(model, block_on(surname))
#' DBI::dbDisconnect(con, shutdown = TRUE)
il_estimate_em <- function(model, blocking, convergence = 1e-5,
                           fix_u = TRUE, fix_m = FALSE,
                           max_iterations = 25L,
                           fix_prior = FALSE,
                           estimate_without_tf = TRUE,
                           derive_prior = FALSE, ...) {
  validate_il_model(model)
  if (!is.numeric(max_iterations) || length(max_iterations) != 1L ||
    max_iterations < 1L || max_iterations != as.integer(max_iterations)) {
    cli::cli_abort('{.arg max_iterations} must be a positive integer.')
  }
  max_iterations <- as.integer(max_iterations)
  if (fix_u && fix_m) {
    cli::cli_abort('At least one of {.arg fix_u} and {.arg fix_m} must be {.code FALSE}.')
  }
  result <- get_pairs_with_gamma_counts(model, list(blocking))

  if (result$n_pairs == 0L) {
    cli::cli_abort('No pairs generated by the blocking rule. Choose a less restrictive rule.')
  }

  comparisons <- model$spec$comparisons
  comp_names <- vapply(comparisons, function(c) c$columns, character(1))
  n_comp <- length(comp_names)
  n_pairs <- result$n_pairs

  # Decide whether to use per-pair TF-inclusive EM
  has_tf <- any(vapply(comparisons, function(c) {
    isTRUE(c$method$term_frequency)
  }, logical(1)))
  use_pair_level <- !estimate_without_tf && has_tf

  # For pair-level EM, retrieve individual pairs with TF data
  pair_tf_data <- NULL
  if (use_pair_level) {
    pair_result <- get_pairs_with_gammas(model, list(blocking))
    if (nrow(pair_result$gamma_mat) == 0L) {
      cli::cli_abort('No pairs generated by the blocking rule. Choose a less restrictive rule.')
    }
  }

  # Column deactivation: identify comparisons that overlap with the

  # blocking rule's columns and exclude them from estimation (splink's
  # approach — blocking on a column means it must match, so gamma is
  # always the highest level and m/u cannot be estimated from the data).
  br_cols <- blocking$columns
  deactivated <- vapply(comparisons, function(c) {
    any(c$columns %in% br_cols)
  }, logical(1))
  trained_names <- comp_names[!deactivated]
  deact_names <- comp_names[deactivated]
  if (length(trained_names) > 0 && length(deact_names) > 0) {
    cli::cli_inform(
      'EM trained: {.field {trained_names}} | skipped (blocked on): {.field {deact_names}}'
    )
  } else if (length(trained_names) > 0) {
    cli::cli_inform('EM trained: {.field {trained_names}}')
  } else {
    cli::cli_inform('EM: all comparisons overlap with the blocking rule; nothing was trained.')
  }

  # Extract gamma patterns and counts (or per-pair gammas for TF mode)
  if (use_pair_level) {
    pattern_mat <- pair_result$gamma_mat
    pattern_mat[is.na(pattern_mat)] <- 0L
    storage.mode(pattern_mat) <- 'integer'
    colnames(pattern_mat) <- comp_names
    pattern_n <- rep(1, nrow(pattern_mat))
    n_patterns <- nrow(pattern_mat)
    pair_tf_data <- pair_result$tf_data
  } else {
    gamma_cols <- paste0('gamma_', comp_names)
    pattern_mat <- as.matrix(result$counts[, gamma_cols, drop = FALSE])
    pattern_mat[is.na(pattern_mat)] <- 0L
    storage.mode(pattern_mat) <- 'integer'
    colnames(pattern_mat) <- comp_names
    pattern_n <- as.numeric(result$counts$n)
    n_patterns <- nrow(pattern_mat)
  }

  # Determine number of gamma levels per comparison
  levels_per_comp <- vapply(comparisons, function(c) n_gamma_levels(c$method), integer(1))

  # Initialize m and u as per-level vectors (list of numeric vectors)
  m_list <- vector('list', n_comp)
  u_list <- vector('list', n_comp)
  names(m_list) <- comp_names
  names(u_list) <- comp_names

  params <- model$params$comparisons
  if (!is.null(params)) {
    if ('level' %in% names(params) && !'gamma_level' %in% names(params)) {
      params <- migrate_params_to_gamma_level(params)
    }
  }

  for (j in seq_len(n_comp)) {
    cn <- comp_names[j]
    nl <- levels_per_comp[j]

    # Default m: high probability for highest level, low for others
    m_default <- rep(0.1 / max(nl - 1L, 1L), nl)
    m_default[nl] <- 0.9
    u_default <- rep(1 / nl, nl)

    if (!is.null(params)) {
      rows <- params[params$comparison == cn, ]
      rows <- rows[order(rows$gamma_level), ]
      if (nrow(rows) == nl) {
        m_vec <- ifelse(is.na(rows$m), m_default, rows$m)
        u_vec <- ifelse(is.na(rows$u), u_default, rows$u)
      } else {
        m_vec <- m_default
        u_vec <- u_default
      }
    } else {
      m_vec <- m_default
      u_vec <- u_default
    }
    m_list[[j]] <- m_vec
    u_list[[j]] <- u_vec
  }

  prior <- safe_prior(model)

  # Blocking-adjusted prior: blocking columns force agreement, enriching
  # the pair population with matches. Adjust the prior upward by the
  # Bayes factors of deactivated comparisons' exact-match levels.
  if (any(deactivated)) {
    prior_bf <- prior / (1 - prior)
    for (j in which(deactivated)) {
      nl <- levels_per_comp[j]
      m_top <- m_list[[j]][nl] # highest gamma level (exact match)
      u_top <- u_list[[j]][nl]
      level_bf <- max(m_top, 1e-10) / max(u_top, 1e-10)
      prior_bf <- prior_bf * level_bf
    }
    prior <- min(max(prior_bf / (1 + prior_bf), 1e-6), 1 - 1e-6)
  }

  max_iter <- max_iterations
  tol <- convergence
  history <- list()

  for (iter in seq_len(max_iter)) {
    # E-step: compute posterior match probability per pattern (not per pair)
    log_match <- rep(log(prior), n_patterns)
    log_nonmatch <- rep(log(1 - prior), n_patterns)

    for (j in seq_len(n_comp)) {
      # Skip deactivated comparisons in E-step — their contribution is
      # already captured by the blocking-adjusted prior (splink removes
      # them from the comparison list entirely).
      if (deactivated[j]) next
      m_vec <- pmax(m_list[[j]], 1e-10)
      u_vec <- pmax(u_list[[j]], 1e-10)
      log_m_vals <- log(m_vec)
      log_u_vals <- log(u_vec)
      idx <- pattern_mat[, j] + 1L
      log_match <- log_match + log_m_vals[idx]
      log_nonmatch <- log_nonmatch + log_u_vals[idx]
    }

    # Per-pair TF adjustment in E-step (only in pair-level mode)
    if (use_pair_level && !is.null(pair_tf_data)) {
      for (j in seq_len(n_comp)) {
        comp <- comparisons[[j]]
        if (!isTRUE(comp$method$term_frequency)) next
        col <- comp$columns
        tf_w <- comp$tf_adjustment_weight %||% 1.0
        if (tf_w == 0) next

        tf_l <- pair_tf_data[[paste0('tf_', col, '_l')]]
        tf_r <- pair_tf_data[[paste0('tf_', col, '_r')]]
        if (is.null(tf_l) || is.null(tf_r)) next

        tf_max <- pmax(tf_l, tf_r, na.rm = TRUE)
        tf_min <- comp$tf_minimum_u_value %||% 0.0
        if (tf_min > 0) tf_max <- pmax(tf_max, tf_min)

        max_level <- n_gamma_levels(comp$method) - 1L
        u_exact <- pmax(u_list[[j]][max_level + 1L], 1e-10)

        mask <- pattern_mat[, j] == max_level & !is.na(tf_max) & tf_max > 0
        if (any(mask)) {
          log_tf_adj <- tf_w * (log(u_exact) - log(tf_max[mask]))
          log_match[mask] <- log_match[mask] + log_tf_adj
        }
      }
    }

    max_log <- pmax(log_match, log_nonmatch)
    weights <- exp(log_match - max_log) /
      (exp(log_match - max_log) + exp(log_nonmatch - max_log))

    # M-step: update m and/or u per-level (weighted by pattern counts)
    sum_w <- sum(weights * pattern_n)
    sum_nw <- sum((1 - weights) * pattern_n)
    old_m_list <- m_list
    old_u_list <- u_list
    old_prior <- prior

    # Update prior unless fixed
    if (!fix_prior) {
      prior <- sum_w / n_pairs
      prior <- max(min(prior, 1 - 1e-6), 1e-6)
    }

    if (!fix_m) {
      for (j in seq_len(n_comp)) {
        if (deactivated[j]) next
        nl <- levels_per_comp[j]
        raw <- numeric(nl)
        for (k in seq(0L, nl - 1L)) {
          mask <- pattern_mat[, j] == k
          raw[k + 1L] <- (sum(weights[mask] * pattern_n[mask]) + 0.5 / nl) / (sum_w + 0.5)
        }
        raw <- pmax(raw, 0.001)
        raw <- raw / sum(raw)
        m_list[[j]] <- raw
      }
    }

    if (!fix_u) {
      for (j in seq_len(n_comp)) {
        if (deactivated[j]) next
        nl <- levels_per_comp[j]
        raw <- numeric(nl)
        for (k in seq(0L, nl - 1L)) {
          mask <- pattern_mat[, j] == k
          raw[k + 1L] <- (sum((1 - weights[mask]) * pattern_n[mask]) + 0.5 / nl) / (sum_nw + 0.5)
        }
        raw <- pmax(raw, 0.001)
        raw <- raw / sum(raw)
        u_list[[j]] <- raw
      }
    }

    history[[iter]] <- tibble::tibble(
      session = length(model$params$history) + 1L,
      iteration = iter,
      comparison = rep(comp_names, times = levels_per_comp),
      gamma_level = unlist(lapply(levels_per_comp, function(nl) seq(0L, nl - 1L))),
      value = unlist(m_list)
    )

    changes <- numeric(0)
    if (!fix_m) {
      changes <- c(changes, vapply(seq_len(n_comp), function(j) {
        max(abs(m_list[[j]] - old_m_list[[j]]))
      }, numeric(1)))
    }
    if (!fix_u) {
      changes <- c(changes, vapply(seq_len(n_comp), function(j) {
        max(abs(u_list[[j]] - old_u_list[[j]]))
      }, numeric(1)))
    }
    if (!fix_prior) {
      changes <- c(changes, abs(prior - old_prior))
    }
    max_change <- max(changes)
    if (max_change < tol) break
  }

  # Store updated parameters
  rows <- list()
  for (j in seq_len(n_comp)) {
    cn <- comp_names[j]
    nl <- levels_per_comp[j]
    for (k in seq(0L, nl - 1L)) {
      rows <- c(rows, list(data.frame(
        comparison = cn,
        gamma_level = k,
        m = m_list[[j]][k + 1L],
        u = u_list[[j]][k + 1L],
        stringsAsFactors = FALSE
      )))
    }
  }
  model$params$comparisons <- tibble::as_tibble(do.call(rbind, rows))

  # Store updated prior if it was estimated
  if (!fix_prior) {
    model$params$prior <- prior
  }

  # Derive prior from trained parameter values
  if (derive_prior) {
    model$params$prior <- derive_prior_from_params(
      m_list, u_list, pattern_mat, pattern_n
    )
  }

  model$params$history <- c(model$params$history, history)
  model$trained <- TRUE
  model
}

#' Derive the prior from trained EM parameters
#'
#' After EM converges, the proportion of expected matches gives an
#' estimate of the prior probability that two random records match.
#'
#' @param m_list List of m probability vectors per comparison.
#' @param u_list List of u probability vectors per comparison.
#' @param pattern_mat Integer matrix of unique gamma patterns.
#' @param pattern_n Numeric vector of counts per pattern.
#' @return Numeric scalar — the derived prior.
#' @noRd
derive_prior_from_params <- function(m_list, u_list, pattern_mat, pattern_n) {
  n_comp <- ncol(pattern_mat)
  n_patterns <- nrow(pattern_mat)
  log_bf <- numeric(n_patterns)
  for (j in seq_len(n_comp)) {
    m_vec <- pmax(m_list[[j]], 1e-10)
    u_vec <- pmax(u_list[[j]], 1e-10)
    idx <- pattern_mat[, j] + 1L
    log_bf <- log_bf + log(m_vec[idx]) - log(u_vec[idx])
  }
  bf <- exp(log_bf)
  # Weighted average posterior match probability with a flat 0.5 prior
  sum((bf / (1 + bf)) * pattern_n) / sum(pattern_n)
}
