#' Train Parameters via Expectation-Maximisation
#'
#' Runs the EM algorithm under a blocking rule to learn m and u parameters
#' from unlabelled data. Multiple calls with different blocking rules can
#' be chained to train on complementary subsets of record pairs — each
#' call updates the model cumulatively.
#'
#' @param model An `il_model` object (piped in).
#' @param blocking A blocking rule created by [block_on()].
#' @param ... Reserved for future options (e.g., convergence tolerance,
#'   maximum iterations).
#'
#' @return An updated `il_model` with trained m and u parameters.
#' @export
#'
#' @examples
#' df <- data.frame(
#'   unique_id = 1:20,
#'   first_name = c("John", "Jon", "Jane", "Jane", "Bob",
#'                   "Bobby", "Alice", "Alicia", "Tom", "Thomas",
#'                   "John", "Jon", "Jane", "Janet", "Bob",
#'                   "Robert", "Alice", "Alison", "Tom", "Tomas"),
#'   surname = c("Smith", "Smith", "Doe", "Doe", "Jones",
#'               "Jones", "Brown", "Brown", "White", "White",
#'               "Smith", "Smyth", "Doe", "Doe", "Jones",
#'               "Jones", "Brown", "Browne", "White", "White"),
#'   dob = c("1990-01-01", "1990-01-01", "1985-06-15", "1985-06-15",
#'           "2000-12-01", "2000-12-01", "1975-03-22", "1975-03-22",
#'           "1988-07-04", "1988-07-04", "1990-01-01", "1990-01-02",
#'           "1985-06-15", "1985-06-16", "2000-12-01", "2000-12-02",
#'           "1975-03-22", "1975-03-23", "1988-07-04", "1988-07-05"),
#'   city = c("London", "London", "Paris", "Paris", "Berlin",
#'            "Berlin", "Rome", "Rome", "Madrid", "Madrid",
#'            "London", "London", "Paris", "Paris", "Berlin",
#'            "Berlin", "Rome", "Rome", "Madrid", "Madrid"),
#'   email = c("john@example.com", "jon@example.com", "jane@example.com",
#'             "jane@example.com", "bob@example.com", "bobby@example.com",
#'             "alice@example.com", "alicia@example.com", "tom@example.com",
#'             "thomas@example.com", "john@example.com", "jon@example.com",
#'             "jane@example.com", "janet@example.com", "bob@example.com",
#'             "robert@example.com", "alice@example.com", "alison@example.com",
#'             "tom@example.com", "tomas@example.com")
#' )
#' con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
#' spec <- il_spec() |>
#'   il_compare(first_name, cl_jaro_winkler(0.9, 0.7)) |>
#'   il_compare(surname, cl_jaro_winkler(0.9, 0.7)) |>
#'   il_compare(dob, cl_exact()) |>
#'   il_block_on(surname) |>
#'   il_block_on(first_name)
#' model <- il_model(df, spec = spec, con = con)
#' model <- il_estimate_u(model)
#'
#' model <- il_estimate_em(model, block_on(surname))
#' DBI::dbDisconnect(con)
il_estimate_em <- function(model, blocking, ...) {
  validate_il_model(model)
  pairs <- get_blocked_pairs(model, blocking)

  if (nrow(pairs) == 0L) {
    cli::cli_abort("No pairs generated by the blocking rule. Choose a less restrictive rule.")
  }

  comparisons <- model$spec$comparisons
  gamma_mat <- compute_gamma_matrix(pairs, comparisons)
  comp_names <- colnames(gamma_mat)
  n_comp <- ncol(gamma_mat)
  n_pairs <- nrow(pairs)

  # Initialize m and u
  params <- model$params$comparisons
  m_match <- rep(0.9, n_comp)
  m_nonmatch <- rep(0.1, n_comp)
  u_match <- rep(0.1, n_comp)
  u_nonmatch <- rep(0.9, n_comp)

  if (!is.null(params)) {
    for (j in seq_len(n_comp)) {
      cn <- comp_names[j]
      row_m <- params[params$comparison == cn & params$level == "match", ]
      row_nm <- params[params$comparison == cn & params$level == "non_match", ]
      if (nrow(row_m) > 0L && !is.na(row_m$m[1])) m_match[j] <- row_m$m[1]
      if (nrow(row_nm) > 0L && !is.na(row_nm$m[1])) m_nonmatch[j] <- row_nm$m[1]
      if (nrow(row_m) > 0L && !is.na(row_m$u[1])) u_match[j] <- row_m$u[1]
      if (nrow(row_nm) > 0L && !is.na(row_nm$u[1])) u_nonmatch[j] <- row_nm$u[1]
    }
  }

  prior <- model$params$prior %||% 0.05
  max_iter <- 25L
  tol <- 1e-5
  history <- list()

  for (iter in seq_len(max_iter)) {
    # E-step: compute posterior match probability via matrix multiply
    log_m1 <- log(pmax(m_match, 1e-10))
    log_m0 <- log(pmax(m_nonmatch, 1e-10))
    log_u1 <- log(pmax(u_match, 1e-10))
    log_u0 <- log(pmax(u_nonmatch, 1e-10))

    log_match    <- log(prior) + as.numeric(gamma_mat %*% (log_m1 - log_m0)) + sum(log_m0)
    log_nonmatch <- log(1 - prior) + as.numeric(gamma_mat %*% (log_u1 - log_u0)) + sum(log_u0)

    max_log <- pmax(log_match, log_nonmatch)
    weights <- exp(log_match - max_log) /
      (exp(log_match - max_log) + exp(log_nonmatch - max_log))

    # M-step: update m via matrix-vector multiply (u stays from estimate_u)
    sum_w <- sum(weights)

    old_m_match <- m_match
    raw <- (as.numeric(crossprod(gamma_mat, weights)) + 0.5) / (sum_w + 1.0)
    m_match <- pmax(pmin(raw, 0.99), 0.01)
    m_nonmatch <- 1 - m_match

    history[[iter]] <- tibble::tibble(
      iteration = iter,
      comparison = comp_names,
      level = "match",
      value = m_match
    )

    if (max(abs(m_match - old_m_match)) < tol) break
  }

  # Store updated parameters
  model$params$comparisons <- tibble::tibble(
    comparison = rep(comp_names, each = 2L),
    level = rep(c("match", "non_match"), times = n_comp),
    m = as.numeric(rbind(m_match, m_nonmatch)),
    u = as.numeric(rbind(u_match, u_nonmatch))
  )

  model$params$history <- c(model$params$history, history)
  model$trained <- TRUE
  model
}
