# Helpers for dependency-aware EM over aggregated comparison patterns.

il_estimate_em_dependency_aware <- function(
  model,
  blocking,
  convergence,
  max_iterations,
  fix_prior,
  fix_u_supplied,
  fix_m_supplied,
  estimate_without_tf_supplied,
  derive_prior,
  has_tf
) {
  comparisons <- model$spec$comparisons
  comp_names <- comparison_names(comparisons)
  deactivated <- vapply(
    comparisons,
    function(c) {
      any(c$columns %in% blocking$columns)
    },
    logical(1)
  )
  validate_dependency_aware_options(
    model,
    fix_prior = fix_prior,
    fix_u_supplied = fix_u_supplied,
    fix_m_supplied = fix_m_supplied,
    estimate_without_tf_supplied = estimate_without_tf_supplied,
    derive_prior = derive_prior,
    has_tf = has_tf,
    deactivated = deactivated,
    comp_names = comp_names
  )

  result <- get_pairs_with_gamma_counts(model, list(blocking))
  if (result$n_pairs == 0L) {
    cli::cli_abort(
      'No pairs generated by the blocking rule. Choose a less restrictive rule.'
    )
  }

  pattern_df <- normalize_dependency_patterns(result$counts, comp_names)
  pattern_n <- as.numeric(pattern_df$n)
  pattern_mat <- as.matrix(pattern_df[, comp_names, drop = FALSE])
  n_patterns <- nrow(pattern_mat)

  levels <- dependency_pattern_levels(pattern_mat, comparisons, comp_names)
  pattern_factors <- dependency_pattern_factors(pattern_mat, levels)
  support_factors <- dependency_support_factors(levels)
  support_mat <- dependency_support_matrix(support_factors)
  support_n <- dependency_support_counts(
    pattern_factors,
    support_factors,
    pattern_n
  )
  observed_idx <- dependency_support_match(pattern_factors, support_factors)

  init <- initialize_dependency_pattern_probs(
    model,
    support_mat,
    support_n,
    comparisons,
    comp_names
  )
  prior <- init$prior
  p_m <- init$p_m
  p_u <- init$p_u

  history <- list()
  fit_m <- NULL
  fit_u <- NULL
  converged <- FALSE
  offset <- 1e-6

  for (iter in seq_len(max_iterations)) {
    old <- c(prior, p_m, p_u)

    log_match <- log(prior) + log(pmax(p_m[observed_idx], 1e-12))
    log_nonmatch <- log1p(-prior) + log(pmax(p_u[observed_idx], 1e-12))
    posterior <- posterior_from_logs(log_match, log_nonmatch)

    sum_w <- sum(posterior * pattern_n)
    prior <- clamp_probability(sum_w / sum(pattern_n))

    fit_m <- fit_dependency_loglinear(
      support_factors,
      dependency_expand_observed_counts(
        posterior * pattern_n,
        observed_idx,
        nrow(support_factors)
      ),
      interactions = FALSE,
      offset = offset
    )
    fit_u <- fit_dependency_loglinear(
      support_factors,
      dependency_expand_observed_counts(
        (1 - posterior) * pattern_n,
        observed_idx,
        nrow(support_factors)
      ),
      interactions = TRUE,
      offset = offset
    )

    p_m <- predict_dependency_distribution(
      fit_m,
      support_factors,
      support_factors
    )
    p_u <- predict_dependency_distribution(
      fit_u,
      support_factors,
      support_factors
    )

    max_change <- max(abs(c(prior, p_m, p_u) - old))
    history[[iter]] <- tibble::tibble(
      session = length(model$params$history) + 1L,
      iteration = iter,
      estimator_mode = 'dependency-aware',
      prior = prior,
      max_change = max_change
    )
    if (max_change < convergence) {
      converged <- TRUE
      break
    }
  }

  if (!converged) {
    cli::cli_warn(
      'Dependency-aware EM reached {.arg max_iterations} without meeting the convergence tolerance.'
    )
  }

  scored <- dependency_pattern_score(
    pattern_mat,
    comp_names,
    list(
      prior = prior,
      matched_fit = fit_m,
      unmatched_fit = fit_u,
      support = support_factors,
      levels = levels
    )
  )
  state <- list(
    estimator_mode = 'dependency-aware',
    prior = prior,
    n_pairs = result$n_pairs,
    comparison_names = comp_names,
    levels = levels,
    formulas = list(
      matched = stats::formula(fit_m),
      unmatched = stats::formula(fit_u)
    ),
    matched_fit = fit_m,
    unmatched_fit = fit_u,
    support = support_factors,
    training_patterns = tibble::as_tibble(cbind(pattern_df, scored)),
    converged = converged,
    iterations = length(history),
    offset = offset
  )

  model$params$prior <- prior
  model$params$estimator_mode <- 'dependency-aware'
  model$params$dependency_aware <- state
  model$params$history <- c(model$params$history, history)
  model$trained <- TRUE
  model
}

validate_dependency_aware_options <- function(
  model,
  fix_prior,
  fix_u_supplied,
  fix_m_supplied,
  estimate_without_tf_supplied,
  derive_prior,
  has_tf,
  deactivated,
  comp_names
) {
  unsupported_controls <- character(0)
  if (isTRUE(fix_u_supplied)) {
    unsupported_controls <- c(unsupported_controls, 'fix_u')
  }
  if (isTRUE(fix_m_supplied)) {
    unsupported_controls <- c(unsupported_controls, 'fix_m')
  }
  if (isTRUE(estimate_without_tf_supplied)) {
    unsupported_controls <- c(unsupported_controls, 'estimate_without_tf')
  }
  if (isTRUE(derive_prior)) {
    unsupported_controls <- c(unsupported_controls, 'derive_prior')
  }
  if (length(unsupported_controls) > 0L) {
    cli::cli_abort(
      'EM control{?s} {.arg {unsupported_controls}} {?is/are} only supported with {.val independent} EM, not {.val dependency-aware} scoring.'
    )
  }
  if (isTRUE(fix_prior)) {
    cli::cli_abort(
      '{.arg fix_prior = TRUE} is not supported with {.val dependency-aware} scoring.'
    )
  }
  priors <- model$params$priors
  if (!is.null(priors) && nrow(priors) > 0L) {
    cli::cli_abort(
      'Regularizing priors are only supported with {.val independent} EM, not {.val dependency-aware} scoring.'
    )
  }
  constraints <- model$params$constraints
  if (!is.null(constraints) && nrow(constraints) > 0L) {
    cli::cli_abort(
      'Fixed field constraints are only supported with {.val independent} EM, not {.val dependency-aware} scoring.'
    )
  }
  if (isTRUE(has_tf)) {
    cli::cli_abort(
      'Term-frequency adjustments are not supported with {.val dependency-aware} scoring.'
    )
  }
  blocked_comparisons <- comp_names[deactivated]
  if (length(blocked_comparisons) > 0L) {
    cli::cli_abort(
      'Dependency-aware EM cannot train comparison{?s} {.field {blocked_comparisons}} because {?it/they} overlap{?s/} with the EM blocking rule.'
    )
  }
}

normalize_dependency_patterns <- function(counts, comp_names) {
  gamma_cols <- paste0('gamma_', comp_names)
  missing <- setdiff(gamma_cols, names(counts))
  if (length(missing) > 0L) {
    cli::cli_abort(
      'Pattern table is missing gamma column{?s}: {.field {missing}}.'
    )
  }
  out <- counts[, c(gamma_cols, 'n'), drop = FALSE]
  names(out) <- c(comp_names, 'n')
  for (cn in comp_names) {
    out[[cn]] <- as.integer(out[[cn]])
  }
  out
}

dependency_pattern_levels <- function(pattern_mat, comparisons, comp_names) {
  out <- vector('list', length(comp_names))
  names(out) <- comp_names
  for (j in seq_along(comp_names)) {
    base <- seq(0L, n_gamma_levels(comparisons[[j]]$method) - 1L)
    if (comparison_has_null_gamma(comparisons[[j]]$method)) {
      base <- c(-1L, base)
    }
    observed <- unique(as.integer(pattern_mat[, j]))
    vals <- sort(unique(c(base, observed)))
    out[[j]] <- as.character(vals)
  }
  out
}

comparison_has_null_gamma <- function(method) {
  identical(method$method, 'levels') &&
    any(vapply(
      method$levels,
      function(level) {
        isTRUE(level$is_null_level)
      },
      logical(1)
    ))
}

dependency_pattern_factors <- function(pattern_mat, levels) {
  out <- as.data.frame(pattern_mat, stringsAsFactors = FALSE)
  for (cn in names(levels)) {
    val <- as.character(out[[cn]])
    unknown <- setdiff(unique(val), levels[[cn]])
    if (length(unknown) > 0L) {
      cli::cli_abort(
        'Pattern column {.field {cn}} contains unsupported level{?s}: {.val {unknown}}.'
      )
    }
    out[[cn]] <- factor(val, levels = levels[[cn]])
  }
  out
}

dependency_support_factors <- function(levels) {
  support <- do.call(
    expand.grid,
    c(
      levels,
      list(
        KEEP.OUT.ATTRS = FALSE,
        stringsAsFactors = FALSE
      )
    )
  )
  for (cn in names(levels)) {
    support[[cn]] <- factor(as.character(support[[cn]]), levels = levels[[cn]])
  }
  support
}

dependency_support_matrix <- function(support_factors) {
  mat <- as.matrix(as.data.frame(lapply(support_factors, function(x) {
    as.integer(as.character(x))
  })))
  colnames(mat) <- names(support_factors)
  storage.mode(mat) <- 'integer'
  mat
}

dependency_support_match <- function(pattern_factors, support_factors) {
  match(
    dependency_pattern_key(pattern_factors),
    dependency_pattern_key(support_factors)
  )
}

dependency_support_counts <- function(
  pattern_factors,
  support_factors,
  pattern_n
) {
  idx <- dependency_support_match(pattern_factors, support_factors)
  out <- numeric(nrow(support_factors))
  for (i in seq_along(idx)) {
    out[idx[i]] <- out[idx[i]] + pattern_n[i]
  }
  out
}

dependency_expand_observed_counts <- function(counts, observed_idx, n_support) {
  out <- numeric(n_support)
  for (i in seq_along(observed_idx)) {
    out[observed_idx[i]] <- out[observed_idx[i]] + counts[i]
  }
  out
}

initialize_dependency_pattern_probs <- function(
  model,
  pattern_mat,
  pattern_n,
  comparisons,
  comp_names
) {
  params <- model$params$comparisons
  levels_per_comp <- vapply(
    comparisons,
    function(c) {
      n_gamma_levels(c$method)
    },
    integer(1)
  )
  if (!is.null(params)) {
    if ('level' %in% names(params) && !'gamma_level' %in% names(params)) {
      params <- migrate_params_to_gamma_level(params)
    }
    has_full <- all(vapply(
      seq_along(comp_names),
      function(j) {
        sum(params$comparison == comp_names[j]) == levels_per_comp[j]
      },
      logical(1)
    ))
  } else {
    has_full <- FALSE
  }

  m_list <- vector('list', length(comp_names))
  u_list <- vector('list', length(comp_names))
  names(m_list) <- comp_names
  names(u_list) <- comp_names
  for (j in seq_along(comp_names)) {
    nl <- levels_per_comp[j]
    m_default <- rep(0.1 / max(nl - 1L, 1L), nl)
    m_default[nl] <- 0.9
    u_default <- rep(1 / nl, nl)
    if (has_full) {
      rows <- params[params$comparison == comp_names[j], , drop = FALSE]
      rows <- rows[order(rows$gamma_level), ]
      m_list[[j]] <- ifelse(is.na(rows$m), m_default, rows$m)
      u_list[[j]] <- ifelse(is.na(rows$u), u_default, rows$u)
    } else {
      m_list[[j]] <- m_default
      u_list[[j]] <- u_default
    }
  }

  log_m <- numeric(nrow(pattern_mat))
  log_u <- numeric(nrow(pattern_mat))
  for (j in seq_along(comp_names)) {
    vals <- pattern_mat[, j]
    observed <- vals >= 0L
    if (any(observed)) {
      log_m[observed] <- log_m[observed] +
        log(pmax(m_list[[j]][vals[observed] + 1L], 1e-12))
      log_u[observed] <- log_u[observed] +
        log(pmax(u_list[[j]][vals[observed] + 1L], 1e-12))
    }
  }
  p_m <- exp(log_m - max(log_m))
  p_m <- p_m / sum(p_m)
  p_u <- exp(log_u - max(log_u))
  p_u <- p_u / sum(p_u)

  list(
    prior = safe_prior(model, default = min(0.1, 1 / sum(pattern_n))),
    p_m = p_m,
    p_u = p_u
  )
}

posterior_from_logs <- function(log_match, log_nonmatch) {
  max_log <- pmax(log_match, log_nonmatch)
  exp(log_match - max_log) /
    (exp(log_match - max_log) + exp(log_nonmatch - max_log))
}

fit_dependency_loglinear <- function(
  pattern_factors,
  weighted_counts,
  interactions,
  offset
) {
  data <- pattern_factors
  data$count <- as.numeric(weighted_counts) + offset
  form <- if (interactions && ncol(pattern_factors) > 1L) {
    stats::as.formula('count ~ (.)^2')
  } else {
    stats::as.formula('count ~ .')
  }
  tryCatch(
    stats::glm(form, data = data, family = stats::quasipoisson()),
    error = function(err) {
      cli::cli_abort(c(
        'Dependency-aware log-linear fit failed.',
        'i' = 'This usually means the aggregated pattern table is too sparse or the comparison states are collinear.',
        'x' = conditionMessage(err)
      ))
    }
  )
}

predict_dependency_distribution <- function(
  fit,
  pattern_factors,
  support_factors
) {
  logwt <- stats::predict(fit, newdata = support_factors, type = 'link')
  logwt <- logwt - max(logwt)
  wt <- exp(logwt)
  probs <- pmax(wt / sum(wt), 1e-12)
  keys <- dependency_pattern_key(pattern_factors)
  support_keys <- dependency_pattern_key(support_factors)
  unname(probs[match(keys, support_keys)])
}

dependency_pattern_score <- function(pattern_mat, comp_names, state) {
  factors <- dependency_pattern_factors(pattern_mat, state$levels)
  p_m <- predict_dependency_distribution(
    state$matched_fit,
    factors,
    state$support
  )
  p_u <- predict_dependency_distribution(
    state$unmatched_fit,
    factors,
    state$support
  )
  prior <- clamp_probability(state$prior)
  log_match <- log(prior) + log(p_m)
  log_nonmatch <- log1p(-prior) + log(p_u)
  posterior <- posterior_from_logs(log_match, log_nonmatch)
  match_weight <- log2(p_m / p_u)
  tibble::tibble(
    p_gamma_m = p_m,
    p_gamma_u = p_u,
    match_weight = match_weight,
    total_match_weight = total_match_weight(match_weight, prior),
    match_probability = posterior
  )
}

dependency_pattern_key <- function(pattern_factors) {
  do.call(paste, c(lapply(pattern_factors, as.character), sep = '\r'))
}

dependency_score_pattern_table <- function(model, patterns) {
  state <- model$params$dependency_aware
  if (is.null(state)) {
    cli::cli_abort('Model does not contain dependency-aware estimator state.')
  }
  comp_names <- state$comparison_names
  gamma_cols <- paste0('gamma_', comp_names)
  if (all(gamma_cols %in% names(patterns))) {
    pattern_mat <- as.matrix(patterns[, gamma_cols, drop = FALSE])
    colnames(pattern_mat) <- comp_names
  } else if (all(comp_names %in% names(patterns))) {
    pattern_mat <- as.matrix(patterns[, comp_names, drop = FALSE])
  } else {
    cli::cli_abort(
      'Pattern table must contain comparison columns {.field {comp_names}} or gamma columns {.field {gamma_cols}}.'
    )
  }
  storage.mode(pattern_mat) <- 'integer'
  scored <- dependency_pattern_score(pattern_mat, comp_names, state)
  tibble::as_tibble(cbind(patterns, scored))
}

dependency_collect_patterns_sql <- function(model, gamma_sql) {
  state <- model$params$dependency_aware
  if (is.null(state)) {
    cli::cli_abort('Model does not contain dependency-aware estimator state.')
  }
  gamma_cols <- paste0('gamma_', state$comparison_names)
  pattern_sql <- glue::glue(
    'SELECT DISTINCT {paste(gamma_cols, collapse = ", ")} ',
    'FROM ({gamma_sql}) AS gamma_pairs'
  )
  patterns <- DBI::dbGetQuery(model$con, pattern_sql)
  if (nrow(patterns) == 0L) {
    return(as.data.frame(matrix(
      integer(0),
      nrow = 0,
      ncol = length(gamma_cols),
      dimnames = list(NULL, gamma_cols)
    )))
  }
  for (col in gamma_cols) {
    patterns[[col]] <- as.integer(patterns[[col]])
  }
  patterns
}

dependency_write_score_lookup <- function(model, patterns, score_tbl = NULL) {
  score_tbl <- score_tbl %||%
    il_table_name(model, 'dependency_scores', il_table_suffix())
  state <- model$params$dependency_aware
  if (is.null(state)) {
    cli::cli_abort('Model does not contain dependency-aware estimator state.')
  }
  gamma_cols <- paste0('gamma_', state$comparison_names)
  pattern_mat <- as.matrix(patterns[, gamma_cols, drop = FALSE])
  storage.mode(pattern_mat) <- 'integer'
  colnames(pattern_mat) <- state$comparison_names
  scored <- dependency_pattern_score(pattern_mat, state$comparison_names, state)
  lookup <- tibble::as_tibble(cbind(
    patterns[, gamma_cols, drop = FALSE],
    scored[, c('match_weight', 'total_match_weight', 'match_probability')]
  ))
  drop_registered(model$con, score_tbl)
  DBI::dbWriteTable(
    model$con,
    score_tbl,
    as.data.frame(lookup),
    overwrite = TRUE
  )
}

build_dependency_scored_query <- function(
  model,
  gamma_sql,
  score_tbl,
  threshold = 0.85,
  threshold_match_weight = NULL
) {
  state <- model$params$dependency_aware
  if (is.null(state)) {
    cli::cli_abort('Model does not contain dependency-aware estimator state.')
  }
  gamma_cols <- paste0('gamma_', state$comparison_names)
  gamma_select <- paste(paste0('gamma_pairs.', gamma_cols), collapse = ', ')
  join_clause <- paste(
    vapply(
      gamma_cols,
      function(col) {
        glue::glue('gamma_pairs.{col} = scores.{col}')
      },
      character(1)
    ),
    collapse = ' AND '
  )
  where_clause <- if (!is.null(threshold_match_weight)) {
    glue::glue('WHERE scores.match_weight >= {threshold_match_weight}')
  } else {
    glue::glue('WHERE scores.match_probability >= {threshold}')
  }
  glue::glue(
    'SELECT DISTINCT gamma_pairs.l_unique_id AS unique_id_l, ',
    'gamma_pairs.r_unique_id AS unique_id_r, ',
    '{gamma_select}, scores.match_weight, scores.total_match_weight, ',
    'scores.match_probability ',
    'FROM ({gamma_sql}) AS gamma_pairs ',
    'INNER JOIN {score_tbl} AS scores ON {join_clause} ',
    '{where_clause}'
  )
}

prepare_dependency_scored_query <- function(
  model,
  gamma_sql,
  threshold = 0.85,
  threshold_match_weight = NULL,
  score_tbl = NULL
) {
  score_tbl <- score_tbl %||%
    il_table_name(model, 'dependency_scores', il_table_suffix())
  patterns <- dependency_collect_patterns_sql(model, gamma_sql)
  if (nrow(patterns) == 0L) {
    return(list(scored_sql = NULL, score_tbl = score_tbl))
  }
  dependency_write_score_lookup(model, patterns, score_tbl = score_tbl)
  list(
    scored_sql = build_dependency_scored_query(
      model,
      gamma_sql = gamma_sql,
      score_tbl = score_tbl,
      threshold = threshold,
      threshold_match_weight = threshold_match_weight
    ),
    score_tbl = score_tbl
  )
}

#' Score Comparison Patterns
#'
#' Scores an aggregated or row-level comparison-pattern table using a trained
#' model. Dependency-aware models use their fitted log-linear pattern state.
#' independent models use the fieldwise m/u parameters.
#'
#' @param model A trained `il_model`.
#' @param patterns A data frame containing either comparison columns named like
#'   the model comparisons or gamma columns named `gamma_<comparison>`.
#'
#' @return A tibble containing the input columns plus `match_weight` and
#'   `total_match_weight`, and `match_probability`.
#' @export
il_score_patterns <- function(model, patterns) {
  validate_il_model(model)
  if (!isTRUE(model$trained)) {
    cli::cli_abort('Model must be trained before scoring patterns.')
  }
  if (identical(model$params$estimator_mode, 'dependency-aware')) {
    return(dependency_score_pattern_table(model, patterns))
  }

  comparisons <- model$spec$comparisons
  comp_names <- comparison_names(comparisons)
  gamma_cols <- paste0('gamma_', comp_names)
  if (all(gamma_cols %in% names(patterns))) {
    gamma_mat <- as.matrix(patterns[, gamma_cols, drop = FALSE])
  } else if (all(comp_names %in% names(patterns))) {
    gamma_mat <- as.matrix(patterns[, comp_names, drop = FALSE])
    colnames(gamma_mat) <- comp_names
  } else {
    cli::cli_abort(
      'Pattern table must contain comparison columns {.field {comp_names}} or gamma columns {.field {gamma_cols}}.'
    )
  }
  storage.mode(gamma_mat) <- 'integer'
  colnames(gamma_mat) <- comp_names
  mu <- extract_mu_vectors(model$params$comparisons, comp_names)
  match_weight <- score_gamma_matrix(gamma_mat, mu)
  tibble::as_tibble(cbind(
    patterns,
    tibble::tibble(
      match_weight = match_weight,
      total_match_weight = total_match_weight(match_weight, safe_prior(model)),
      match_probability = weight_to_probability(match_weight, safe_prior(model))
    )
  ))
}
